### PR TITLE
added new native, belongs to NETWORK namespace

### PR DESCRIPTION
**Pull request by Maestro-1337**
func_3079() on freemode.ysc (Line 257273)

### CODE REVIEW

**Comment by alloc8or** [comment]
First off, thanks for this, I completely forgot to check the latest build since it's technically only a minor patch.
However, that native is ``NETWORK_IS_SCRIPT_ACTIVE_BY_HASH`` (we know this from RDR) and should be directly below ``NETWORK_IS_SCRIPT_ACTIVE``. So the first param is a ``Hash`` (the script name hash) and the last param is an ``int``.

**Comment by Maestro-1337** [comment]
ah thanks for correcting me, i've never messed with rdr that's why i couldn't get the right params

**Comment by alloc8or** [comment]
You forgot to move it to its actual position (between ``NETWORK_IS_SCRIPT_ACTIVE`` and ``NETWORK_GET_NUM_SCRIPT_PARTICIPANTS``).

**Comment by Maestro-1337** [comment]
done

**Comment by alloc8or** [comment]
Oh sorry, it should be _above_ ``0x560B423D73015E77``, so directly below ``NETWORK_IS_SCRIPT_ACTIVE_BY_HASH``.

**Pull request merged**
