### PR TITLE
Document 0x4CAFEBFA21EC188D

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

**Comment by alloc8or** [comment]
Do you know how this one differs from ``_LOCK_RADIO_STATION`` (other than that it doesn't work in SP)?
Alphabetically it comes before ``SET_RADIO_STATION_MUSIC_ONLY`` so my initial guess was something like ``SET_RADIO_STATION_LOCKED`` but then I remembered there's ``_LOCK_RADIO_STATION`` already.

**Comment by Sainan** [comment]
I do know that `_LOCK_RADIO_STATION` does not work to hide talk02 and LSUR.

**Comment by Sainan** [comment]
Also, how do you assert their alphabetical order?

**Comment by alloc8or** [comment]
The functions are placed in alphabetical order in the executable. Note that this is not always accurate, e.g. if the actual function name differs from the native name or a native was renamed and we still use the orignal name.

**Comment by Sainan** [comment]
Ah makes sense, I did think about how MSVC does kind of leak this sort of information by being very lazy, but I thought I was just being pedantic and it didn't have any real-world use cases. xD

**Comment by alloc8or** [comment]
Naming natives alphabetically correct makes guessing other names easier and there's a higher chance that the guessed name is the real name or at least very similar. Hence my suggestion to name it ``_SET_RADIO_STATION_ENABLED[_ON_WHEEL]`` or something better if you can think of anything more fitting.

**Comment by Sainan** [comment]
Since it is used or the new "Radio Station Favorites" feature, it might also be called `_SET_RADIO_STATION_FAVORITE`. I do think "visible" is less confusing for anyone using this as an API documentation, but I guess that's what the comments are for.

**Comment by alloc8or** [comment]
Good point. Or... what about _SET_RADIO_STATION\_**IS**_VISIBLE? Would still have "visible" in the name and be more correct in terms of alphabetical order.

**Comment by Sainan** [comment]
Sounds good.

**Pull request merged**
