### PR TITLE
b2802 research

### PR DESCRIPTION
**Pull request by fingaweg**

### CODE REVIEW

**Comment by gottfriedleibniz** [comment]
Is `0x5815BD2763178DF4` correct? 

It looks to toggle some flags that route through the vehicle lighting bits (e.g., similar to `SET_VEHICLE_BRAKE_LIGHTS` and `SET_VEHICLE_FORCE_INTERIORLIGHT`).

Maybe it disables tail lights? Would require me to actually test/verify this.

**Comment by alloc8or** [comment]
You are absolutely correct. I somehow missed that one and only saw the PLAYSTATS natives.
Not sure what @fingaweg did there, but I'll probably push an update soon™ to fix this, along with some other stuff too.

**Comment by fingaweg** [comment]
this was a bait to make gottfried show themselves from the dark

**Comment by gottfriedleibniz** [comment]
I suspect this is already being done, but here is what I have crossed referenced with gamecode:

```
0x170911F37F646F29 = REGISTER_POSTFX_BULLET_IMPACT
0xB7EF5850C39FABCA = SET_PARTICLE_FX_NON_LOOPED_SCALE
0xCF1247CC86961FD6 = GET_ENTITY_BONE_OBJECT_POSITION 
0xA75EE4F689B85391 = _GET_LAST_ENTITY_HIT_BY_ENTITY
0xC2AB6BFE34E92F8B = LOAD_ALL_PATH_NODES
0x5D583F71C901F2A3 = GET_CUTSCENE_PLAY_DURATION
0x923A293361DF44E5 = LOWER_FORKLIFT_FORKS
0x5815BD2763178DF4 = SET_VEHICLE_TAIL_LIGHTS
0x80D9D32636369C92 = _GET_VEHICLE_TRAILER_ATTACHMENT
0x04BD27B5ACB67067 = _NETWORK_GET_RANDOM_FLOAT_RANGED
0xDD7CEF5B3A4DA8A6 = IS_NETWORK_VEHICLE_RUNNING_RESPOT_TIMER
0x96320E6549DAE7B4 = SET_REMOTE_PLAYER_VISIBLE_IN_CUTSCENE
0x3DAD00265FBF356B = NETWORK_SET_CURRENT_CHAT_OPTION
0xAD4326FCA30D62F8 = NETWORK_IS_PLAYER_ON_BLOCKLIST
0x007FDE5A7897E426 = RESET_FACIAL_IDLE_ANIM
0xAC0BB4D87777CAE2 = SET_PED_WETNESS
0xD19C0826DC20CF1C = ARE_CREDITS_RUNNING
0x3DA8C28346B62CED = GET_COORDS_OF_PROJECTILE_TYPE_IN_ANGLED_AREA
0x89DA85D949CE57A0 = DONT_ZOOM_MINIMAP_WHEN_RUNNING_THIS_FRAME
```

**Comment by alloc8or** [comment]
Thanks @gottfriedleibniz. Yeah, that's exactly what I was planning to add soon.

**Pull request merged**
