### PR TITLE
Fix duplicate "entity" parameters in WAYPOINT_PLAYBACK_START_SHOOTING_AT_PED

### PR DESCRIPTION
**Pull request by WithLithum**
The commit simply renames two `entity` parameters in WAYPOINT_PLAYBACK_START_SHOOTING_AT_PED to `entity1` and `entity2`.

### CODE REVIEW

**Comment by alloc8or** [comment]
Looks like #205 changed these params to `Ped ped`. Still duplicates though...

**Comment by slavexe** [comment]
I'm pretty sure the second parameter should be renamed to ```Ped target``` as that makes logical sense based off how R* uses this native in the scripts. That way it would match what I did in #205 for the second parameter of ```TASK::WAYPOINT_PLAYBACK_START_AIMING_AT_PED```.

**Comment by kagikn** [comment]
#208 changes the signature to `void WAYPOINT_PLAYBACK_START_SHOOTING_AT_PED(Ped iPed, Ped iTargetPed, BOOL bRunAndGun, BOOL FiringPatternHash)` as the leak says expect the 4th parameter type in #208 is wrong (should be `Hash`).

**Comment by alloc8or** [comment]
Merged #214 for now, as I just want it fixed atm and can't be bothered to resolve the conflicts.

**Pull request closed without merging**
