### PR TITLE
Research 0xE67C6DFD386EA5E7

### PR DESCRIPTION
**Pull request by Kekeke1337**
I have researched the functionality that displays a text saying cash/bank before your balance, when you start playing GTA Online for the first time, in order to figure out which one is which.
For context, this is what I mean; https://i.imgur.com/MiYUtNl.png

This native is extremely simple, it just sets certain bool. The code that handles the money balance HUD in the check for whether to use the functionality mentioned above

### CODE REVIEW

**Comment by Kekeke1337** [comment]
I am not sure why 6 commits are amended here, but the changes are what I intend for, so it's fine I suppose?

**Comment by alloc8or** [comment]
I've actually tried to find a name for this one several times over the years and found `ALLOW_CASH_WHILE_SCALEFORM_PAINT` a while ago but still not sure whether that's a collision or not.

**Comment by Kekeke1337** [comment]
My guess is that it's just a very good collision. Like it describes it perfectly and has the same hash, but the name is far from anything else R* has used, so I doubt it. I think we're better off with a name like mine until someone finds the real one.

**Comment by gottfriedleibniz** [comment]
Is the joaat for this native correctly mapped from console? Asking because it is close to the `*_FAKE_MP_CASH` natives that were recently updated (`0x6253B9D7` and `0xE319F90B`).

One potential collision: `0x5476b9fd = DISPLAY_CASH_AND_DRAW_PARENT`

**Comment by Kekeke1337** [comment]
No idea tbh. If you want to look it up yourself, it's pretty easy to find. Look for the `MENU_PLYR_CASH` or `MENU_PLYR_BANK` text labels. You'll see an if statement that checks certain bool before concatenating.

**Comment by Kekeke1337** [comment]
Hey. Is there any reason that this pull request is yet to be merged (or closed)? Is it perhaps the fact that somehow I pushed all commits? If so, I've tried squashing them, but the Github app wouldn't let me, since I have this pull request open. Should I close this and make a new one?

**Comment by alloc8or** [comment]
Will probably merge this later today.

**Pull request merged**
