### PR TITLE
Update _SET_ENTITY_ANGULAR_VELOCITY

### PR DESCRIPTION
**Pull request by ufteers**

### CODE REVIEW

**Comment by alloc8or** [comment]
Did you find the real name somewhere or is this a guessed name? (in which case it should be prefixed with an underscore)

**Comment by ufteers** [comment]
> Did you find the real name somewhere or is this a guessed name? (in which case it should be prefixed with an underscore)

I think this is the real name, because GET_ENTITY_ROTATION_VELOCITY returns the value that this method sets. I can add an underscore if necessary.

**Comment by gottfriedleibniz** [comment]
According to the compilation order, its name is likely between `SET_ENTITY_ALWAYS_PRERENDER` and `SET_ENTITY_ANIM_CURRENT_TIME`. 

Additionally, their naming convention seems to use 'angular velocity' as the vector quantity of rotation... Well, besides `0x213B91045D09B983` (and some corona bits). Which lead to my choice in names.

**Comment by ufteers** [comment]
Ok, thanks for the info, closing the pull request.

**Comment by veletok** [comment]
Харви лох

**Pull request closed without merging**
